FROM amd64/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN apt-get update && apt-get install -y bash net-tools && apt-get clean

RUN useradd -ms /bin/bash clore

RUN mkdir /etc/clore

RUN mkdir /var/lib/clore

RUN chown clore:clore /etc/clore /var/lib/clore

WORKDIR /home/clore

COPY --chown=clore:clore linux64/* /home/clore/

COPY --chown=clore:clore run.sh /home/clore/

USER clore

CMD ["/home/clore/run.sh"]
